### ISSUE TITLE
Negative numbers in arrays break the parser

### ISSUE THREAD

**Issue by johanokl** [mjansson/json#1]
Works:
JSON: ```[[100.0,100.0],[100.0,200.0],[200.0,100.0],[200.0,200.0],[150.0,100.0],[150.0,200.0],[250.0,100.0],[250.0,200.0],[200.0,100.0],[200.0,200.0],[300.0,100.0],[300.0,200.0]]```
Returns 37 tokens.

Doesn't work:
JSON: ```[[-100.0,-50.0],[-100.0,50.0],[0.0,-50.0],[0.0,50.0],[-50.0,-50.0],[-50.0,50.0],[50.0,-50.0],[50.0,50.0],[0.0,-50.0],[0.0,50.0],[100.0,-50.0],[100.0,50.0]]```
Returns 0 tokens.

Both arrays are marked valid by http://jsonlint.com.

**Comment by mjansson** [comment]
comitted a fix to the number parser in [eca4112](https://github.com/rampantpixels/json_lib/commit/eca41124ccae808415b0fcc732ff82815704b531)

**Comment by johanokl** [comment]
Verified as fixed. Thanks.
